### ISSUE TITLE
incompatibility with ie11 and certain outlook versions

### ISSUE THREAD

**Issue by ZainW** [davecra/easyEWS#12] opened 2020-08-25 14:04 UTC
https://github.com/davecra/easyEWS/blob/132a02fafd8148538e964a0e399abde027aa41cd/easyEws.js#L217

Hi there David,

 looks like you are using some fancy ES6 syntax on this line, and therefore we cannot use this in our app as we need to support outlook 2013/2016 where they still use ie11 or lower as the engine for webaddins

**Comment by kishor1910** [comment] 2020-08-26 13:05
Hi @davecra, facing similar issue on outlook web-addin with IE v11 or windows outlook app...`sendMailItem` function doesn't load properly...PFA the error screenshot.
![Screenshot 2020-08-26 at 6 13 25 PM](https://user-images.githubusercontent.com/65155177/91306799-b38d1880-e7ca-11ea-8417-d4ddb9adb523.png)
![Screenshot 2020-08-26 at 6 13 47 PM](https://user-images.githubusercontent.com/65155177/91306808-b5ef7280-e7ca-11ea-99cb-5d44bccd0b67.png)


Thanks.

**Comment by davecra** [comment] 2020-08-27 19:53
Updated this and confirmed it now works on IE6. 

The sendMail function now takes a single object, see the documentation on this. I tried to keep it as original to form as possible so someone can still inline the object if they want. Please confirm if you are able to get this to work.

NOTE: I also took the opportunity to update this function per multiple other requests to allow for HTML types and FILE type attachments rather than just message items. Another one I did not get to was defining multiple recipient lines (To/CC/BCC), that will be in a future update once I find the best way to implement that on the recipients object.

Please confirm issue is resolved and I will close it out.

**Comment by kishor1910** [comment] 2020-08-31 08:56
@davecra Thanks for the changes...i followed the docs but getting these errors
`Uncaught TypeError: easyEws.SimpleAttachmentObject is not a constructor`
`Uncaught TypeError: easyEws.SendMailFunctionObject is not a function`

**Comment by kishor1910** [comment] 2020-09-03 07:33
Hi @davecra any update on this ?...will it support IE11 as well?

**Comment by davecra** [comment] 2020-09-03 19:28
Sorry, I have not had time to get around to this yet. 

Originally, I tested this in IE11 and it worked for me and the code in the function is from my test. But I will test and verify again. 

I might not have time to get to it until this weekend or early next week, but will update this as soon as I have the results.

**Comment by davecra** [comment] 2020-09-03 22:55
I was able to get to this today. 

I tested in OWA/Office 365 on IE11 and it worked. Here is the version of IE11:

![image](https://user-images.githubusercontent.com/19915160/92180265-9c76a800-ee14-11ea-927f-bfbb50442c85.png)

Here is the exact code from my Taskpane.js:

```javascript
/// <reference path="../../node_modules/easyews/easyEws.js"/>
/* global document, Office, console, easyEws, SendMailFunctionObject,SimpleAttachmentObject */
Office.onReady(info => {
  if (info.host === Office.HostType.Outlook) {
    document.getElementById("sideload-msg").style.display = "none";
    document.getElementById("app-body").style.display = "flex";
    document.getElementById("run").onclick = run;
  }
});
export async function run() {
  const message = {
    type: Office.MailboxEnums.ItemNotificationMessageType.InformationalMessage,
    message: "The message has been sent.",
    icon: "Icon.80x80",
    persistent: true
  };
  /**@type {SimpleAttachmentObject} */
  var att = new SimpleAttachmentObject("welcome_packet.txt", "SGVsbG8gd29ybGQh", "file");
  /**@type {SendMailFunctionObject} */
  var p = new SendMailFunctionObject("Simple Subject", 
                                     "<b>Welcome</b> and hello World!", 
                                     "html", 
                                      ["testing@contoso.com"], 
                                      [att], "sentitems", 
                                      function(result) {
                                        // Show a notification message
                                        console.log(result);
                                        Office.context.mailbox.item.notificationMessages.replaceAsync("action", message);
                                      }, function(error) {
                                        console.log(error);
                                      }, function(debug) {
                                        console.log(debug);
                                      });
  easyEws.sendMailItem(p);
}
```

This is a very simple READ Outlook Add-in, with only a taskpane and a Run button on the taskpane (essentially the default created Yeoman project for a Read Add-in and I pulled in easyEws with NPM). I also tried using the CDN just in case there was some strange IE11 behavior there and it still worked fine for me.

Can you confirm your version of IE you have and also which client (OWA or Outlook) are you using?

**Comment by kishor1910** [comment] 2020-09-10 06:21
@davecra Thanks much David for trying and detailed explanation, it works for me as well in my angular project, with adding the function SendMailFunctionObject and SimpleAttachmentObject in my local, it was not able to locate these two objects. 
But with this change it works fine in IE11 but doesn't work in windows outlook 2019 version.

**Comment by davecra** [comment] 2020-09-10 13:50
What is the specific version of Outlook 2019? Also are you using the volume license version of Office 2019 or Retail?

Here are the release versions:
https://docs.microsoft.com/en-us/officeupdates/update-history-office-2019

And according to this page:
https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

If you are on **16.0.13127.20082** or greater then this is using the Edge controls, not IE. If you are on the latest build, you should be able to use the Edge Tools Preview to debug the task pane:
https://www.microsoft.com/en-us/p/microsoft-edge-devtools-preview/9mzbfrmz0mnj

Currently, I do not have a copy of Outlook 2019 to test against. I would need to setup a VM and verify. I do have Office 365 Outlook and it did work for me there. So if it is working in one and not the other then there might be a problem in the particular build you are on. Are these the specific errors you are still getting in Outlook 2019?

- Uncaught TypeError: easyEws.SimpleAttachmentObject is not a constructor
- Uncaught TypeError: easyEws.SendMailFunctionObject is not a function

Or, are you getting a different error in Outlook 2019?

I will work on testing this again in Office 365 Outlook first just to verify that everything still works and then work towards getting a VM with Office 2019 setup once I know the specific edition/version you have.

**Comment by davecra** [comment] 2020-09-16 16:05
Tested with latest build of Office 2019/Outlook full-client in a Windows 10 (latest) VM and was unable to repro.

Closing this as resolved for initial reports and because the last issue with Outlook 2019 is not able to be reproduced. 

If this is still an issue for you, please reopen and I will investigate further with you. Some suggestions based on research was to test the load order of the easyEws.js library versus other libraries you are using to make sure it is loaded in time for the moment it needs to be used.

**Closed as completed by davecra** 2020-09-16 16:05 UTC
